const GET_POKEMON = "GET_POKEMON"
const GET_BY_NAME = "GET_BY_NAME"
const GET_BY_ID = "GET_BY_ID"
const SET_FILTER = "SET_FILTER"
const GET_TYPES = "GET_TYPES"
const GET_CREATED = "GET_CREATED"
const GET_SORT = "GET_SORT"
const ADD_FAVORITES = "ADD_FAVORITES"
const DELETE_FAVORITE = "DELETE_FAVORITE"



export{
    GET_POKEMON,
    GET_BY_NAME,
    GET_BY_ID,
    SET_FILTER,
    GET_TYPES,
    GET_CREATED,
    GET_SORT,
    ADD_FAVORITES,
    DELETE_FAVORITE
}